MyBeerCRMApp/Models/Beer.cs
namespace MyBeerCRMApp.Models
{
    public class Beer
    {
        public int id { get; set; }
        
        public string? name { get; set; }
        
        public int quantity { get; set; }

    }
}

MyBeerCRMApp/Controllers/BeerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBeerCRMApp.Models;

using System.Xml.Linq;

namespace MyBeerCRMApp.Controllers
{
    [Authorize]
    public class BeerController : Controller
    {
        ApplicationContext db;
        public BeerController(ApplicationContext context)
        {
            db = context;
        }

        public async Task<IActionResult> BeerIndex()
        {

            return View(await db.beers.ToListAsync());
        }

        
        

        public IActionResult CreateBeer()
        {

            return View();
        }
        

        [HttpPost]

        public async Task<IActionResult> CreateBeer(Beer beer)
        {
            db.beers.Add(beer);
            await db.SaveChangesAsync();
            return Redirect("BeerIndex");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBeer(int? id) //Крайний раз написали делете
        {
            if (id != null)
            {
                Beer? beer = db.beers.FirstOrDefault(x => x.id == id);
                
                if (beer != null)
                {
                    db.beers.Remove(beer);
                    await db.SaveChangesAsync();
                    return RedirectToAction("BeerIndex");
                }
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult>BeerEdit(int? id)
        {
            if (id != null)
            {
                Beer? beer = db.beers.FirstOrDefault(x=>x.id == id);
                if (beer != null) return View(beer);
                
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> BeerEdit(Beer beer)
        {
            db.beers.Update(beer);
            db.SaveChangesAsync();
            return RedirectToAction("BeerIndex");
        }
    }
}

MyBeerCRMApp/Views/Beer/BeerEdit.cshtml
@model MyBeerCRMApp.Models.Beer

<h2>Редактирование пива</h2>

<form asp-asp-controller="Beer" asp-action="BeerEdit" asp-route-id ="@Model.id">

    <p>
        <label asp-for="name">Название пива</label><br />
        <input type="text" asp-for="name" />
    </p>

    <p>
        <label asp-for="quantity">Количество пива</label><br/>
        <input type="number" asp-for ="quantity"/>
    </p>

    <p>
        <input type="submit" value="Обновить" />
    </p>

</form>

MyBeerCRMApp/Views/Beer/BeerIndex.cshtml
@model IEnumerable<MyBeerCRMApp.Models.Beer>

<h2>Список пива</h2>
<p><a asp-action="createBeer">Добавить пиво</a></p>
<table class="table">
    <tr>
        <th>
          Идентификационный номер          @*Написать реализацию для сорта айди*@
         </th>

        <th>
            <a asp-action="BeerSort" asp-route-sortStateBeer="@ViewBag.NameSort"> Название пива</a>
          
        </th>

        <th>
            <a asp-action="BeerSort" asp-route-sortStateBeer="@ViewBag.QuantitySort">  Количество пива </a>
            </th>
    
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.id</td>
            <td>@item.name</td>
            <td>@item.quantity</td>

            <td> 
                <a asp-action="BeerEdit" asp-controller="Beer" asp-route-id="@item.id">Изменить</a>
            </td>
            <td>
                <form asp-controller="Beer" asp-action="DeleteBeer" method="post" asp-route-id="@item.id">
                    <input type="submit" value="Удалить" />

                </form>

            </td>


        </tr>
    }
</table>

MyBeerCRMApp/Views/Beer/CreateBeer.cshtml
@model MyBeerCRMApp.Models.Beer

<h2>Добавление пиво</h2>
<form asp-action="createBeer" asp-controller="Beer">
    <p>
        <label asp-for="name">Название пива</label><br />
        <input type="text" asp-for="name" />
    </p>
    <p>
        <label asp-for="quantity">Объем</label><br />
        <input type="text" asp-for="quantity" />
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>