MyBeerCRMApp/Controllers/CalcController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBeerCRMApp.Migrations;
using MyBeerCRMApp.Models;

namespace MyBeerCRMApp.Controllers
{
    public class CalcController : Controller
    {
        ApplicationContext db;
        
        [Authorize]
        public IActionResult Calculate()
        {
            return View(new CalcModel());
        }

        [HttpPost]
        [Authorize]

        
        public IActionResult Calculate(CalcModel c, string calculate)
        {
            if (calculate == "Calculate_Beer")
            {
                c.Total = c.Calc_BeerPrice * c.Calc_BeerQuantity;
            }
            else if (calculate == "Calculate_Change")
            {
                c.Change = c.Cash - c.Total;
            }
            
            

            return View(c);
        }
       
    }
}

MyBeerCRMApp/Views/Calc/Calculate.cshtml
@model MyBeerCRMApp.Models.CalcModel


<html>
    <head>


    </head>


    <body>
        <h2>Calculate Beer</h2>


        <div class="row">
        @using (Html.BeginForm("Calculate", "Calc", FormMethod.Post))
        {
            <div class="form-group">

                <label for="Calc_BeerPrice"> Beer Price </label>
                <input type="text" class="form-control" id="Calc_BeerPrice" name="Calc_BeerPrice" value="@Model.Calc_BeerPrice">


            </div>

            <div class="form-group">

                <label for="Calc_BeerQuantity"> Beer Quantity </label>
                <input type="text" class="form-control" id="Calc_BeerQuantity" name="Calc_BeerQuantity" value="@Model.Calc_BeerQuantity">


            </div>


            <div class="form-group">

                <label for="Total"> Total </label>
                <input type="text" class="form-control" id="Total" name="Total" value="@Model.Total">


            </div>

            <div class="form-group">

                <label for="Cash"> Cash </label>
                <input type="text" class="form-control" id="Cash" name="Cash" value="@Model.Cash">


            </div>

            <div class="form-group">

                <label for="Change"> Change </label>
                <input type="text" class="form-control" id="Change" name="Change" value="@Model.Change">


            </div>

            <button type="submit" class="btn btn-info" id="CalculateBeer" value="Calculate_Beer" name="Calculate">Calculate Beer</button>

            <button type="submit" class="btn btn-warning" id="CalculateChange" value="Calculate_Change" name="Calculate">Calculate Change</button>
        }
    </div>
    </body>















</html>